FROM resin/%%RESIN_MACHINE_NAME%%-golang:1.8 as builder
WORKDIR /go/src/yuna
COPY *.go ./
RUN go get ./...
RUN CGO_ENABLED=0 GOOS=linux go install -a

FROM scratch
COPY --from=builder /go/bin/yuna /yuna
CMD ["/yuna"]